export type { AppTransport, RpcErrorData, RuntimeEvent, } from "./contracts/transport.ts";
export { RpcError } from "./contracts/transport.ts";
export { rpcWithContract } from "./contracts/typed-rpc.ts";
export { createMagnisClient } from "./client.ts";
export type { MagnisClient, MagnisClientOptions } from "./client.ts";
export type { MagnisPlatform, MagnisStorage, FetchImplementation, WebSocketCloseEvent, WebSocketErrorEvent, WebSocketFactory, WebSocketLike, WebSocketMessageEvent, WorkspaceConnectionSeed, WorkspaceConnectionSource, } from "./platform.ts";
export { MutableExternalResource } from "./resource.ts";
export type { ExternalResource, ResourceListener } from "./resource.ts";
export type { ClientError, ResourceStatus } from "./errors.ts";
export type { WorkspaceConnection, WorkspaceConnections, WorkspaceConnectionsResource, } from "./workspaces/resource.ts";
export type { MagnisSession, MagnisSessionStatus, SessionResource, } from "./session/resource.ts";
export type { ConnectionResource, MagnisConnection, } from "./connection/resource.ts";
export { createEpisodeRegistry, MagnisEpisodeRegistry } from "./episodes/registry.ts";
export type { EpisodeRegistry } from "./episodes/registry.ts";
export type { CreateEpisodeInput, AgentImplementationOption, AgentImplementationOptions, EpisodeCollection, EpisodeCollectionResource, } from "./episodes/collection.ts";
export { episodePreview, selectEpisodeList, } from "./episodes/list.ts";
export type { EpisodeListFilter, EpisodeListQuery, EpisodeListRow, } from "./episodes/list.ts";
export type { EpisodeMetadata, EpisodeMetadataResource, EpisodeMessaging, EpisodeMessagingResource, EpisodeResource, EpisodeSendInput, EpisodeTools, EpisodeToolsResource, } from "./episodes/resource.ts";
export { EpisodeContextSlice, deduplicateEpisodeContext, } from "./episodes/context.ts";
export type { EpisodeContext, EpisodeContextEntity, EpisodeContextResource, } from "./episodes/context.ts";
export { EpisodeTodoSlice } from "./episodes/todo.ts";
export type { EpisodeTodo, EpisodeTodoResource } from "./episodes/todo.ts";
export { EpisodeUsageSlice } from "./episodes/usage.ts";
export type { EpisodeUsage, EpisodeUsageResource } from "./episodes/usage.ts";
export { projectEpisodeTools } from "./episodes/tools.ts";
export type { EpisodeToolProjection, ToolCardModel } from "./episodes/tools.ts";
export { runHeadlessEpisodeTurn } from "./episodes/headless-turn.ts";
export type { HeadlessEpisodeTurnEvent, HeadlessEpisodeTurnOptions, } from "./episodes/headless-turn.ts";
export { HttpClientError, httpRequest, httpWithContract, type HttpRequestOptions, } from "./transport/http.ts";
export { exportWorkspace, importWorkspace } from "./workspace.ts";
export type { TokenBreakdown } from "./contracts/billing.ts";
export { emptyTokenBreakdown } from "./contracts/billing.ts";
export type { AgentContextDescriptor, AgentInvocationInput, AgentDraftRequest, AgentHistoryBlock, AgentTodoItem, AllowlistTarget, AgentContextAction, AgentRuntimeState, AgentChatStoreApi, } from "./contracts/agent-core.ts";
export type { ChatMessageAttachment, EntityMention, EntitySearchResult, ChatMessage, ReplyToContext, UIContext, ToolCallEvent, ToolResultEvent, PendingToolCall, CompletedToolResult, ContentBlock, AgentFailure, EpisodeState, AskUserOption, AskUserQuestion, AskUserTab, AskUserPayload, AgentChat, AgentMessage, AgentModuleData, PendingPromptKind, PendingPrompt, AskUserAnswer, ResolvedDecision, } from "./types/episode.ts";
export type { EpisodeListItem, EpisodeMessage } from "@magnis/sdk";
export { agentFailureMessage } from "./types/episode.ts";
export { ASK_USER_MARKER_PREFIX, ASK_USER_MARKER_CLOSER, ASK_USER_TOOL_NAMES, buildAskUserPairings, isAskUserName, resolveDecisionForToolCall, selectPendingPromptQueue, selectSupersededToolCallIds, wrapAskUserAnswer, } from "./approvals/index.ts";
export type { ApprovalReadState, PendingPromptQueueOptions } from "./approvals/index.ts";
export type { SyncSurfaceStatus, SourceAccount, SourceListResponse, SourceAccountsListResponse, EnumOption, ModuleSettingFieldType, ModuleSettingField, ModuleSettingsSchema, ModuleSettingValue, ModuleSettingsEntry, } from "./types/settings.ts";
export type { Account, AccountState, AuthLossReason, Cursor, ItemCount, PriorSuccess, RepairAction, SourceAuthKind, SourceStatus, SourceStatusListResponse, SurfaceSync, SyncError, SyncReport, SyncRun, TotalEstimate, VerifiedAuth, } from "./types/source-status.ts";
export { normalizeSchemaId } from "./util/normalizeSchemaId.ts";
export { buildCopyPayload, extractArgSummary, extractEntities, extractResultCount, extractResultCountLabel, humanizeToolName, inferSchemaFromTool, isHiddenTool, projectEntityCards, resolveCardFields, rpcNameForToolCall, stripMcpPrefix, toolNamesEquivalent, toolResultError, TOOL_ERROR_MARKER, } from "./presentation/index.ts";
export type { EntityCardProjection, ExtractEntitiesOptions, } from "./presentation/index.ts";
export { AgentChatStore, createEmptyEpisodeState, parseTodoItems, parseUserMessageAttachments, } from "./agent/AgentChatStore.ts";
export { queryEpisodeUsage } from "./agent/episode-usage.ts";
export type { Listener, TodoItem, TodoListener, TodoSnapshot, } from "./agent/AgentChatStore.ts";
export { MAX_BACKOFF_MS, RPC_TIMEOUT_MS, RPC_STREAM_TIMEOUT_MS, } from "./transport/constants.ts";
export { adaptWebSocket, WebSocketClient } from "./transport/WebSocketClient.ts";
export type { Rpc, StreamEvent, ConnectionStatus, WebSocketClientOptions, } from "./transport/WebSocketClient.ts";
