export declare const prepareSearchAblationContract: import("./contract.js").HttpContract<"POST", "/api/eval/search-ablation/prepare", import("zod").ZodObject<{
    stateSha256: import("zod").ZodString;
    corpusSha256: import("zod").ZodObject<{
        p1: import("zod").ZodString;
        p235: import("zod").ZodString;
    }, import("zod/v4/core").$strict>;
    modelId: import("zod").ZodLiteral<"search-ablation-bge-small-en-v1.5">;
    schemas: import("zod").ZodArray<import("zod").ZodObject<{
        id: import("zod").ZodString;
        version: import("zod").ZodNumber;
        description: import("zod").ZodString;
        jsonSchema: import("zod").ZodType<import("../index.js").JsonValue, unknown, import("zod/v4/core").$ZodTypeInternals<import("../index.js").JsonValue, unknown>>;
    }, import("zod/v4/core").$strict>>;
    declarations: import("zod").ZodArray<import("zod").ZodObject<{
        prefix: import("zod").ZodString;
        toml: import("zod").ZodString;
    }, import("zod/v4/core").$strict>>;
    entityBatches: import("zod").ZodArray<import("zod").ZodArray<import("zod").ZodObject<{
        ref: import("zod").ZodString;
        schemaId: import("zod").ZodString;
        name: import("zod").ZodNullable<import("zod").ZodString>;
        occurredAt: import("zod").ZodNullable<import("zod").ZodString>;
        properties: import("zod").ZodType<import("../index.js").JsonValue, unknown, import("zod/v4/core").$ZodTypeInternals<import("../index.js").JsonValue, unknown>>;
    }, import("zod/v4/core").$strict>>>;
    links: import("zod").ZodArray<import("zod").ZodObject<{
        fromRef: import("zod").ZodString;
        toRef: import("zod").ZodString;
        kind: import("zod").ZodString;
    }, import("zod/v4/core").$strict>>;
}, import("zod/v4/core").$strict>, import("zod").ZodObject<{
    userId: import("zod").ZodString;
    generation: import("zod").ZodNumber;
    modelId: import("zod").ZodString;
    modelRevision: import("zod").ZodString;
    dimensions: import("zod").ZodNumber;
    embeddingProbeSha256: import("zod").ZodString;
    indexPolicyFingerprint: import("zod").ZodString;
    stateSha256: import("zod").ZodString;
    indexed: import("zod").ZodNumber;
    total: import("zod").ZodNumber;
}, import("zod/v4/core").$strict>>;
export declare const runSearchAblationPairContract: import("./contract.js").HttpContract<"POST", "/api/eval/search-ablation/pair", import("zod").ZodObject<{
    caseId: import("zod").ZodString;
    query: import("zod").ZodString;
    schemaIds: import("zod").ZodArray<import("zod").ZodString>;
    typedTool: import("zod").ZodString;
    typedArguments: import("zod").ZodNullable<import("zod").ZodType<import("../index.js").JsonValue, unknown, import("zod/v4/core").$ZodTypeInternals<import("../index.js").JsonValue, unknown>>>;
    topK: import("zod").ZodNumber;
    contextByteCap: import("zod").ZodNumber;
    expectedGeneration: import("zod").ZodNumber;
}, import("zod/v4/core").$strict>, import("zod").ZodObject<{
    caseId: import("zod").ZodString;
    flat: import("zod").ZodObject<{
        generation: import("zod").ZodNumber;
        modelId: import("zod").ZodString;
        modelRevision: import("zod").ZodString;
        dimensions: import("zod").ZodNumber;
        embeddingProbeSha256: import("zod").ZodString;
        indexPolicyFingerprint: import("zod").ZodString;
        query: import("zod").ZodString;
        topK: import("zod").ZodNumber;
        contextByteCap: import("zod").ZodNumber;
        hits: import("zod").ZodArray<import("zod").ZodObject<{
            ref: import("zod").ZodString;
            rank: import("zod").ZodNumber;
            score: import("zod").ZodNumber;
            channel: import("zod").ZodEnum<{
                text: "text";
                semantic: "semantic";
                hybrid: "hybrid";
            }>;
            chunkIndex: import("zod").ZodNumber;
            excerpt: import("zod").ZodString;
            contextBytes: import("zod").ZodNumber;
        }, import("zod/v4/core").$strict>>;
    }, import("zod/v4/core").$strict>;
    typed: import("zod").ZodObject<{
        generation: import("zod").ZodNumber;
        modelId: import("zod").ZodString;
        modelRevision: import("zod").ZodString;
        dimensions: import("zod").ZodNumber;
        embeddingProbeSha256: import("zod").ZodString;
        indexPolicyFingerprint: import("zod").ZodString;
        query: import("zod").ZodString;
        topK: import("zod").ZodNumber;
        contextByteCap: import("zod").ZodNumber;
        hits: import("zod").ZodArray<import("zod").ZodObject<{
            ref: import("zod").ZodString;
            rank: import("zod").ZodNumber;
            score: import("zod").ZodNumber;
            channel: import("zod").ZodEnum<{
                text: "text";
                semantic: "semantic";
                hybrid: "hybrid";
            }>;
            chunkIndex: import("zod").ZodNumber;
            excerpt: import("zod").ZodString;
            contextBytes: import("zod").ZodNumber;
        }, import("zod/v4/core").$strict>>;
    }, import("zod/v4/core").$strict>;
}, import("zod/v4/core").$strict>>;
export declare const searchAblationHttpContracts: readonly [import("./contract.js").HttpContract<"POST", "/api/eval/search-ablation/prepare", import("zod").ZodObject<{
    stateSha256: import("zod").ZodString;
    corpusSha256: import("zod").ZodObject<{
        p1: import("zod").ZodString;
        p235: import("zod").ZodString;
    }, import("zod/v4/core").$strict>;
    modelId: import("zod").ZodLiteral<"search-ablation-bge-small-en-v1.5">;
    schemas: import("zod").ZodArray<import("zod").ZodObject<{
        id: import("zod").ZodString;
        version: import("zod").ZodNumber;
        description: import("zod").ZodString;
        jsonSchema: import("zod").ZodType<import("../index.js").JsonValue, unknown, import("zod/v4/core").$ZodTypeInternals<import("../index.js").JsonValue, unknown>>;
    }, import("zod/v4/core").$strict>>;
    declarations: import("zod").ZodArray<import("zod").ZodObject<{
        prefix: import("zod").ZodString;
        toml: import("zod").ZodString;
    }, import("zod/v4/core").$strict>>;
    entityBatches: import("zod").ZodArray<import("zod").ZodArray<import("zod").ZodObject<{
        ref: import("zod").ZodString;
        schemaId: import("zod").ZodString;
        name: import("zod").ZodNullable<import("zod").ZodString>;
        occurredAt: import("zod").ZodNullable<import("zod").ZodString>;
        properties: import("zod").ZodType<import("../index.js").JsonValue, unknown, import("zod/v4/core").$ZodTypeInternals<import("../index.js").JsonValue, unknown>>;
    }, import("zod/v4/core").$strict>>>;
    links: import("zod").ZodArray<import("zod").ZodObject<{
        fromRef: import("zod").ZodString;
        toRef: import("zod").ZodString;
        kind: import("zod").ZodString;
    }, import("zod/v4/core").$strict>>;
}, import("zod/v4/core").$strict>, import("zod").ZodObject<{
    userId: import("zod").ZodString;
    generation: import("zod").ZodNumber;
    modelId: import("zod").ZodString;
    modelRevision: import("zod").ZodString;
    dimensions: import("zod").ZodNumber;
    embeddingProbeSha256: import("zod").ZodString;
    indexPolicyFingerprint: import("zod").ZodString;
    stateSha256: import("zod").ZodString;
    indexed: import("zod").ZodNumber;
    total: import("zod").ZodNumber;
}, import("zod/v4/core").$strict>>, import("./contract.js").HttpContract<"POST", "/api/eval/search-ablation/pair", import("zod").ZodObject<{
    caseId: import("zod").ZodString;
    query: import("zod").ZodString;
    schemaIds: import("zod").ZodArray<import("zod").ZodString>;
    typedTool: import("zod").ZodString;
    typedArguments: import("zod").ZodNullable<import("zod").ZodType<import("../index.js").JsonValue, unknown, import("zod/v4/core").$ZodTypeInternals<import("../index.js").JsonValue, unknown>>>;
    topK: import("zod").ZodNumber;
    contextByteCap: import("zod").ZodNumber;
    expectedGeneration: import("zod").ZodNumber;
}, import("zod/v4/core").$strict>, import("zod").ZodObject<{
    caseId: import("zod").ZodString;
    flat: import("zod").ZodObject<{
        generation: import("zod").ZodNumber;
        modelId: import("zod").ZodString;
        modelRevision: import("zod").ZodString;
        dimensions: import("zod").ZodNumber;
        embeddingProbeSha256: import("zod").ZodString;
        indexPolicyFingerprint: import("zod").ZodString;
        query: import("zod").ZodString;
        topK: import("zod").ZodNumber;
        contextByteCap: import("zod").ZodNumber;
        hits: import("zod").ZodArray<import("zod").ZodObject<{
            ref: import("zod").ZodString;
            rank: import("zod").ZodNumber;
            score: import("zod").ZodNumber;
            channel: import("zod").ZodEnum<{
                text: "text";
                semantic: "semantic";
                hybrid: "hybrid";
            }>;
            chunkIndex: import("zod").ZodNumber;
            excerpt: import("zod").ZodString;
            contextBytes: import("zod").ZodNumber;
        }, import("zod/v4/core").$strict>>;
    }, import("zod/v4/core").$strict>;
    typed: import("zod").ZodObject<{
        generation: import("zod").ZodNumber;
        modelId: import("zod").ZodString;
        modelRevision: import("zod").ZodString;
        dimensions: import("zod").ZodNumber;
        embeddingProbeSha256: import("zod").ZodString;
        indexPolicyFingerprint: import("zod").ZodString;
        query: import("zod").ZodString;
        topK: import("zod").ZodNumber;
        contextByteCap: import("zod").ZodNumber;
        hits: import("zod").ZodArray<import("zod").ZodObject<{
            ref: import("zod").ZodString;
            rank: import("zod").ZodNumber;
            score: import("zod").ZodNumber;
            channel: import("zod").ZodEnum<{
                text: "text";
                semantic: "semantic";
                hybrid: "hybrid";
            }>;
            chunkIndex: import("zod").ZodNumber;
            excerpt: import("zod").ZodString;
            contextBytes: import("zod").ZodNumber;
        }, import("zod/v4/core").$strict>>;
    }, import("zod/v4/core").$strict>;
}, import("zod/v4/core").$strict>>];
//# sourceMappingURL=search-ablation.d.ts.map